In [65]:
# Neural network; OOP and functional approach

import numpy as np
import matplotlib.pyplot as plt
import sympy as sym
from sympy import *
import math

In [2]:
inputs = np.array([[0, 1, 0],
                   [0, 1, 1],
                   [0, 0, 0],
                   [1, 0, 0],
                   [1, 1, 1],
                   [1, 0, 1]])

outputs = np.array([[0], [0], [0], [1], [1], [1]])

In [17]:
class NeuralNetwork:

    def __init__(self, inputs, outputs):
        self.inputs  = inputs
        self.outputs = outputs
        self.weights = np.array([[.50], [.50], [.50]])
        self.error_history = []
        self.epoch_list = []

In [20]:
# define function, sigmoid, logistic
def sigmoid(self, x, deriv=False):
    if deriv == True:
        return x * (1 - x)
    return 1 / (1 + np.exp(-x))

#sym.diff(1/1 + sym.exp(-x))

In [22]:
# outputs hidden layer guess, starts with sum of feature * weight. input * weight matrix * sigmoid function = probabilty btw 0-1
# X (input matrix) * w (Weights) = sum(xw) = sum(xw)
def feed_forward(self):
    self.hidden = self.sigmoid(np.dot(self.inputs, self.weights))

In [49]:
#functional approach
X = np.array([[0,0,1], [0,1,0], [1,0,1]])
ouputs = [0,0,1,1]

def neural_net (inputs, outputs):
    inputs = inputs
    outputs = outputs

def sigmoidftn(x):
    return 1 / (1 + np.exp(-x))
def sigmoidder(x):
    x = sym.Symbol('x')
    return sym.diff(1 / (1 + sym.exp(-x)))

X = np.array([[0,0,1], [0,1,0], [1,0,1], [1,1,1]]) # input data
w = [0.5, 0.5, 0.5] # arbitrary weights set

d = np.dot(X, w) # dot product of input and weights

#one training iteration, prediction of hidden layer
hidden = sigmoidftn(d)

#calculate error of hidden layer's prediction
error = hidden - outputs

error
hidden

array([0.62245933, 0.62245933, 0.73105858, 0.81757448])

In [69]:
x = sym.Symbol('x')
der_of_sigmoid = sym.diff(1 / (1 + sym.exp(-x))) # derivative of sigmoid function

sigder = lambdify(x, der_of_sigmoid)
#error * dersigmoids
sigder(d)

array([0.23500371, 0.23500371, 0.19661193, 0.14914645])

In [24]:
# go through layers of neural net, indicate weight contributions to output/error, change weight based on gradient of hidden layers output.
def backpropagation(self):
    self.error  = self.outputs - self.hidden
    delta = self.error * self.sigmoid(self.hidden, deriv=True)
    self.weights += np.dot(self.inputs.T, delta)

array([[0. , 0. , 0.5],
       [0. , 0.5, 0. ],
       [0.5, 0. , 0.5]])

SyntaxError: invalid syntax (<ipython-input-29-bb2c6e590aaf>, line 1)